### ISSUE TITLE
API Keys Visible

### ISSUE THREAD

**Issue by IceCereal** [saakethtypes/Pewds-vs-Tseries#1]
Hey, your api keys are visible in your code. https://github.com/saakethtypes/Pewds-vs-Tseries/blob/af1e35d5a4872ec4eb5de600a9cc81cb0e827c0b/pewds_vs_tseries.py#L10 https://github.com/saakethtypes/Pewds-vs-Tseries/blob/af1e35d5a4872ec4eb5de600a9cc81cb0e827c0b/pewds_vs_tseries.py#L31 If someone uses it, they can use your bot account. You should delete this repository and create a `TOKEN` file instead which you can `.gitignore`. 

Look at this [My Bot](https://github.com/IceCereal/Bot_REGOD-New/blob/afd79b3cefd4374b3290f4d0207a37b4fd9062e4/regod.py#L25) and the way I've read it from a file called `TOKEN`. 

Best solution is to delete this repository and commit everything again.

**Comment by saakethtypes** [comment]
fixed it
